- hosts: all
  roles:
    - role: server
      tags: server

    - role: keycloak
      tags: keycloak

    - role: phplist
      tags: phplist

    - role: geerlingguy.nginx
      become: yes
      vars:
        nginx_remove_default_vhost: true
        nginx_upstreams:
          - name: php-handler
            #strategy: "ip_hash" # "least_conn", etc.
            #keepalive: 16 # optional
            servers: {
              "127.0.0.1:9000",
              unix: /var/run/php/php7.4-fpm.sock
            }
        nginx_vhosts:
          - listen: "443 ssl"
            server_name: "{{ keycloak_domain }}"
            #root: '{{root}}'
            #access_log: ""
            state: "present"
            filename: "keycloak.conf"
            extra_parameters: |
              location / {
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_pass http://127.0.0.1:8080;
              }
              ssl_certificate     /etc/letsencrypt/live/{{ keycloak_domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ keycloak_domain }}/privkey.pem;
              ssl_protocols       TLSv1.1 TLSv1.2;
              ssl_ciphers         HIGH:!aNULL:!MD5;

          - listen: "80"
            server_name: "{{ keycloak_domain }}"
            return: "301 https://{{ keycloak_domain }}$request_uri"
            filename: "keycloak.80.conf"
            state: "present"

          - listen: "443 ssl"
            server_name: "{{ phplist_domain }}"
            error_log: "/var/log/nginx/phplist-error.log"
            state: "present"
            filename: "phplist.conf"
            extra_parameters: |
              ssl_certificate     /etc/letsencrypt/live/{{ keycloak_domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ keycloak_domain }}/privkey.pem;

              # source https://www.nginx.com/resources/wiki/start/topics/recipes/phplist/
              #
              root {{ phplist_root }};
              index index.php;
              charset utf-8;

              location ~* \.(txt|log|inc)$ {
                  allow 127.0.0.1;
                  deny all;
              }

              location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                expires max;
                log_not_found off;
              }

              #block phplist config directory
              location /config {
                  deny all;
              }

              location / {
                  rewrite ^ /index.php$request_uri;
              }

              #per the phplist .htaccess these are the only public allowed php files
              location ~* (index\.php|upload\.php|connector\.php|dl\.php|ut\.php|lt\.php|download\.php)$ {
                     fastcgi_split_path_info ^(.|\.php)(/.+)$;

                     include fastcgi_params; #standar fastcgi config file
                     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                     fastcgi_intercept_errors on;
                     fastcgi_pass php-handler;
              }


              #block all other php file access from public
              location ~ \.php$ {
                 deny all;
              }


          - listen: "80"
            server_name: "{{ phplist_domain }}"
            return: "301 https://{{ phplist_domain }}$request_uri"
            filename: "phplist.80.conf"
            state: "present"

      tags: nginx
